<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Edit $block */
?>
<?php
$helper = $this->helper('Themecafe\CustomerRegister\Helper\Data');
if($block->getCustomer()->getEmail()){
    $defaultEmail = explode('@',trim($block->escapeHtml($helper->getConfig('themecafe_customer_verification/general/default_email'))));

    $subject = $block->escapeHtml($block->getCustomer()->getEmail());
    $pattern = '/^('.$defaultEmail[0].')[0-9]+@('.$defaultEmail[1].')*$/';
    $emailStatus = "";
    if(preg_match($pattern, $subject)){
        $emailStatus = __(" (This is a system generated ID, please update your own email ID.)");
    }
}
//$isActive = $helper->getConfig('themecafe_customer_verification/general/active_otp');
$loader = $block->getViewFileUrl('/')."/Themecafe_CustomerRegister/images/loader-1.gif";
?>
<form class="form form-edit-account" action="<?php /* @escapeNotVerified */ echo $block->getUrl('themecafe_otpverification/account/editPost') ?>" method="post" id="form-validate" enctype="multipart/form-data" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>" autocomplete="off">
    <fieldset class="fieldset info">
        <?php echo $block->getBlockHtml('formkey')?>
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Account Information') ?></span></legend><br>
        <?php echo $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')->setObject($block->getCustomer())->toHtml() ?>
        <div class="field email required">
            <label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label><span class="use-10-digit"><?php echo $emailStatus; ?></span>
            <div class="control">
                <input type="email" name="email" id="email" value="<?php echo $block->escapeHtml($block->getCustomer()->getEmail()) ?>" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" class="input-text" data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>
        <?php $themecafevalue = ""; ?>
            <?php if($block->getCustomer()->getCustomAttribute('themecafe_mobile')): ?>
                <?php if($block->getCustomer()->getCustomAttribute('themecafe_mobile')->getValue()):?>
                    <?php $themecafevalue = $block->getCustomer()->getCustomAttribute('themecafe_mobile')->getValue(); ?>
                <?php endif; ?>
            <?php endif; ?>
        <div class="field themecafe_mobile required">
           <label class="label" for="themecafe_mobile"><span><?php /* @escapeNotVerified */ echo __('Mobile Number')?></span></label>
            <div class="control themecafe_control">
                <input type="text" name="themecafe_mobile" id="themecafe_mobile" value="<?php echo $themecafevalue;?>" title="<?php /* @escapeNotVerified */ echo __('Mobile Number') ?>" class="input-text myaccountmobile validate-length" data-validate="{required:true, 'validate-digits':true }">
                <span id="loader" style="display:none">
                <img src="<?php echo $loader;?>" alt="loading.." />
            </span>
                <?php $themecafeMobileVerify = 0;?>
                <?php if ($block->getCustomer()->getCustomAttribute('themecafe_mobile_verify')): ?>
                    <?php if ($block->getCustomer()->getCustomAttribute('themecafe_mobile_verify')->getValue()): ?>
                        <?php $themecafeMobileVerify = 1;?>
                    <?php else: ?>
                        <?php $themecafeMobileVerify = 0;?>
                    <?php endif; ?>
                <?php endif; ?>
            </div>
           <div id="mobile-message" class="otp-message"></div>
        </div>
	<?php // if($isActive):?>
        <div class="field themecafe_mobile_verify required" id="themecafe_verify"  style="display:none;">
            <label for="themecafe_mobile_verify" class="label"><span><?php echo $block->escapeHtml($helper->titleLabel()); ?></span></label>
            <input type="hidden" name="themecafe_mobile_verify" id="themecafe_mobile_verify" value="<?php echo $themecafeMobileVerify;?>">
            <input type="hidden" name="verified_mobile" id="verified_mobile" value="">
            <div id="otp-wrapper">
                <div class="otp-verification-block required" style="" id="otp-block">    
                    <input type="text" name="otpvalue" data-validate="{required:true}" id="otpvalue" class="input-text otp-input"  style="width:100px;"  />
                    <button class="action otp-resend-button" id="resend" type="button" >
                        <span><?php /* @escapeNotVerified */echo __('Resend') ?></span>
                    </button>
                    <div class="otp-tag-line"><i><?php /* @escapeNotVerified */echo __('You have to verify within 5 minutes, Otherwise OTP will expire'); ?></i></div>
                    <div id="otp-message" class="otp-message"></div>
                </div>
            </div>
        </div>
	<?php // endif; ?>
        <?php $_dob = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob') ?>
        <?php $_taxvat = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Taxvat') ?>
        <?php $_gender = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Gender') ?>
        <?php if ($_dob->isEnabled()): ?>
            <?php echo $_dob->setDate($block->getCustomer()->getDob())->toHtml() ?>
        <?php endif ?>
        <?php if ($_taxvat->isEnabled()): ?>
            <?php echo $_taxvat->setTaxvat($block->getCustomer()->getTaxvat())->toHtml() ?>
        <?php endif ?>
        <?php if ($_gender->isEnabled()): ?>
            <?php echo $_gender->setGender($block->getCustomer()->getGender())->toHtml() ?>
        <?php endif ?>
        <div class="field choice">
            <input type="checkbox" name="change_password" id="change-password" value="1" title="<?php /* @escapeNotVerified */ echo __('Change Password') ?>"<?php if ($block->getChangePassword()): ?> checked="checked"<?php endif; ?> class="checkbox"/>
            <label class="label" for="change-password"><span><?php /* @escapeNotVerified */ echo __('Change Password') ?></span></label>
        </div>
    </fieldset>

    <fieldset class="fieldset password">
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Change Password') ?></span></legend><br>
        <div class="field password current required">
            <label class="label" for="current-password"><span><?php /* @escapeNotVerified */ echo __('Current Password') ?></span></label>
            <div class="control">
                <input type="password" class="input-text" name="current_password" id="current-password" autocomplete="off">
            </div>
        </div>
        <div class="field new password required">
            <label class="label" for="password"><span><?php /* @escapeNotVerified */ echo __('New Password') ?></span></label>
            <div class="control">
                <input type="password" class="input-text" name="password" id="password" autocomplete="off">
            </div>
        </div>
        <div class="field confirm password required">
            <label class="label" for="password-confirmation"><span><?php /* @escapeNotVerified */ echo __('Confirm New Password') ?></span></label>
            <div class="control">
                <input type="password" class="input-text" name="password_confirmation" id="password-confirmation" autocomplete="off">
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action save primary" title="<?php /* @escapeNotVerified */ echo __('Save') ?>"><span><?php /* @escapeNotVerified */ echo __('Save') ?></span></button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>"><span><?php /* @escapeNotVerified */ echo __('Go back') ?></span></a>
        </div>
    </div>
</form>
<script>
require([
    'jquery',
    'mage/mage'
], function($){
        $('button#resend').css({left: $('input[name="otpvalue"]').width()+ 27 +'px'});
        var CustomerMobileNumber = "";
        <?php if($block->getCustomer()->getCustomAttribute('themecafe_mobile')):?>
        <?php if($block->getCustomer()->getCustomAttribute('themecafe_mobile')->getValue()):?>
        CustomerMobileNumber = <?php echo $block->escapeHtml($block->getCustomer()->getCustomAttribute('themecafe_mobile')->getValue()); ?>;
        <?php else: ?>
        CustomerMobileNumber = "";
        <?php endif; ?>
        <?php endif; ?>
        $('input[name="themecafe_mobile"]').on('input change', function() {
            <?php if($themecafevalue): ?>
            var customerMobile = <?php echo $themecafevalue;?>;
            <?php else: ?>
            var customerMobile = "";
            <?php endif; ?>
            var mobileVerify = <?php echo $themecafeMobileVerify; ?>;
            if(customerMobile == $(this).val()){
                if(mobileVerify){
                    $('#verified').css("display", "inline-block");
                }
                else{
                    $('#notverified').css("display", "inline-block");
                }
                $('#themecafe_verify').css("display", "none");
            }
            else{
                
                $('#verified').css("display", "none");
                $('#themecafe_verify').css("display", "block");
                $('#notverified').css("display", "none");
            }
        });
$('input[name="themecafe_mobile"]').keypress(function (e) {
            var regex = new RegExp("^[0-9-]+$");
            var str = String.fromCharCode(!e.charCode ? e.which : e.charCode);
            var keycode1 = (e.keyCode ? e.keyCode : e.which);
//            if (regex.test(str) || (keycode1 == 0 || keycode1 == 9 || keycode1 == 8)) {
            if (regex.test(str) || (keycode1 == 0 || keycode1 == 9 || keycode1 == 8 || keycode1 == 116)) {
                return true;
            }
            e.preventDefault();
            return false;
        });
        $('input[name="themecafe_mobile"]').change(function(){
            $('input[name="themecafe_mobile"]').validation();
  	    if($('input[name="themecafe_mobile"]').validation('isValid')){
                send();
	    }
        });
        $('input[name="otpvalue"]').change(function(){
            $('input[name="otpvalue"]').validation();
  	    if($('input[name="otpvalue"]').validation('isValid')){
                verify();
	    }
        });
        $("#otpvalue").focusout(function() {
            $("#otpvalue").css({'border-color': '#d1d1d1'});
        });
        function verify(){
            var NewMobileNumber = $('input[name="themecafe_mobile"]').val();
            if(NewMobileNumber != CustomerMobileNumber){
                $.ajax({
                    url: "<?php echo $this->getUrl("themecafe_otpverification/frontend/otpverify"); ?>",
                    data: {'otpvalue': $('#otpvalue').val(),'themecafeMobilenumber':$('input[name="themecafe_mobile"]').val()},
                    type: 'post',
                    dataType: 'json',
                    showLoader: true,
                    success: function (res) {
                        $('#themecafe_mobile_verify').val(res.response);
                        $('#otp-message').css("display", "block");
                        if (res.response) {
                            $("#otpvalue").css({'border-color': '#8dc041'});
                            $('#otp-message').html('<div class="message-success success message"><div>'+$.mage.__('Your OTP is successfully verified.')+'</div></div>');
                            $('#verified_mobile').val(res.contactnumber);
                        } else {
                            $("#otpvalue").css({'border-color': '#ed8380'});
                            $('#otp-message').html('<div class="message-error error message"><div>'+$.mage.__('Your OTP is incorrect or expired, Please enter correct OTP or Resend again.')+'</div></div>');
                            $('#verified_mobile').val('');
                        }
//                        setTimeout(function() {
//                            $("#otp-message").hide('blind', {}, 1000);
//                        }, 10000);
                    }
                });
            }
        }
        function send(){
            var NewMobileNumber = $('input[name="themecafe_mobile"]').val();
            if(NewMobileNumber != CustomerMobileNumber){
                if (window.matchMedia('(max-width: 767px)').matches) {
                    $('#themecafe_mobile').css("width", "87%");
                }
                $('#loader').css("display", "inline-block");
                $("#otp-message").css("display", "none");
                $("#otpvalue").val('');
                $("#otpvalue").css({'border-color': '#d1d1d1'});
                $('#themecafe_mobile_verify').val(0);
                $.ajax({
                    url: "<?php echo $this->getUrl("themecafe_otpverification/frontend/otpsend"); ?>",
                    data:  {'themecafeMobilenumber':$('input[name="themecafe_mobile"]').val(),'customerEdit':1},
                    type: "POST",
                    dataType: 'json'
                }).done(function (res) {
                    $('#loader').css("display", "none");
                    if (window.matchMedia('(max-width: 767px)').matches) {
                        $('#themecafe_mobile').css("width", "100%");
                    }
                    $('#mobile-message').css("display", "block");
                    $('#mobile-message').html('<span>&nbsp;</span>'+res.messages);
                    setTimeout(function() {
                        $("#mobile-message").hide('blind', {}, 1000);
                    }, 10000);
                });
            }
        }
	$( "#resend" ).click(function() {
            $('input[name="themecafe_mobile"]').validation();
  	    if($('input[name="themecafe_mobile"]').validation('isValid')){
                send();
	    }
	});
	$('#form-validate').submit(function() {
            if($('#form-validate').validation('isValid')){
                var NewMobileNumber = $('input[name="themecafe_mobile"]').val();
                if(NewMobileNumber != CustomerMobileNumber){
                    if($('#verified_mobile').val() != $('#themecafe_mobile').val() || !$('#themecafe_mobile_verify').val() || !$('#verified_mobile').val()){
                        $('#otp-message').css("display", "block");
                        $('#otp-message').html('<div class="message-error error message"><div><?php echo __('Mobile number is not verified'); ?></div></div>');
//                        setTimeout(function() {
//                            $("#otp-message").hide('blind', {}, 500);
//                        }, 5000);
                        return false;
                    }
                }
            }
	});
});
</script>
<?php // endif;?>
<script>
    require([
        "jquery",
        "mage/mage"
    ], function($){
        var dataForm = $('#form-validate');
        var ignore = <?php /* @escapeNotVerified */ echo $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null'; ?>;
        
        dataForm.mage('validation', {
        <?php if ($_dob->isEnabled()): ?>
            errorPlacement: function(error, element) {
                if (element.prop('id').search('full') !== -1) {
                    var dobElement = $(element).parents('.customer-dob'),
                        errorClass = error.prop('class');
                    error.insertAfter(element.parent());
                    dobElement.find('.validate-custom').addClass(errorClass)
                        .after('<div class="' + errorClass + '"></div>');
                }
                else {
                    error.insertAfter(element);
                }
            },
            ignore: ':hidden:not(' + ignore + ')'
        <?php else: ?>
            ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
        <?php endif ?>
        });

    });
</script>
<script type="text/x-magento-init">
    {
        "#change-password": {
            "setPassword": {
                "currentPasswordId": "#current-password",
                "passwordId": "#password",
                "confirmationId": "#password-confirmation",
                "passwordContainer": "fieldset.fieldset.password",
                "showOnDefault": <?php /* @escapeNotVerified */ echo $block->getChangePassword() ? 'true' : 'false' ?>
            }
        }
    }
</script>
