<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block \Magento\Customer\Block\Account\Forgotpassword
 */

// @codingStandardsIgnoreFile
?>
<form class="form password forget"
      action="<?php /* @escapeNotVerified */ echo $block->getUrl('themecafe_otpverification/account/forgotpasswordpost') ?>"
      method="post"
      id="form-validate"
      data-mage-init='{"validation":{}}'>
      <div class="forget-top-img">
            <?php $url = $block->getUrl("pub/media/wysiwyg/"); $url = str_replace("index.php/","",$url);?>
        <img src="<?php echo $url ?>forget-img.png"/>
        <h3>Forgot your password?</h3>
        <span>No problem!</span>
      </div>
    <fieldset class="fieldset" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
        <div class="field note"><?php /* @escapeNotVerified */ echo __('We will send you a PIN to reset your password. Just enter the same phone number you used for registration on elryan.com'); ?></div>
        <div class="field email required">
            <label for="email_address" class="label"><span><?php /* @escapeNotVerified */ echo __('Email / Mobile Number') ?></span></label>
            <div class="control">
                <input type="text" name="email" alt="email" id="email_address" class="input-text" value="<?php echo $block->escapeHtml($block->getEmailValue()) ?>" data-validate="{required:true}" placeholder="<?php /* @escapeNotVerified */ echo __('Mobile Phone') ?>">
            </div>
        </div>
        <!-- <?php // echo $block->getChildHtml('form_additional_info'); ?> -->
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary"><span><?php /* @escapeNotVerified */ echo __('SEND SMS') ?></span></button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?php /* @escapeNotVerified */ echo $block->getLoginUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Go back') ?></span></a>
        </div>
    </div>
</form>
