<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<?php
/**
 * Customer login form template
 *
 * @see \Magento\Customer\Block\Form\Login
 * @var $block \Magento\Customer\Block\Form\Login
 */
?>
<div class="block block-customer-login">
    <div class="block-title">
        <strong id="block-customer-login-heading" role="heading" aria-level="2"><?php // /* @escapeNotVerified */ echo __('Registered Customers') ?></strong>
        <?php $url = $block->getUrl("pub/media/wysiwyg/"); $url = str_replace("index.php/","",$url);?>
        <img src="<?php echo $url ?>login-img.png"/>
    </div>
    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <form class="form form-login"
              action="<?php /* @escapeNotVerified */ echo $block->getPostActionUrl() ?>"
              method="post"
              id="login-form"
              data-mage-init='{"validation":{}}'>
            <?php echo $block->getBlockHtml('formkey'); ?>
            <fieldset class="fieldset login" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
                <div class="field note"><?php /* @escapeNotVerified */ echo __('Do you already have an account?') ?></div>
                <div class="field note2"><?php /* @escapeNotVerified */ echo __('Please enter your sign in details below') ?></div>
                <div class="field email required">
                    <label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Email / Mobile Number') ?></span></label>
                    <div class="control">
                        <input name="login[username]" value="<?php echo $block->escapeHtml($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?> id="email" type="text" class="input-text" title="<?php /* @escapeNotVerified */ echo __('Email / Mobile Number') ?>" data-validate="{required:true}" placeholder="<?php /* @escapeNotVerified */ echo __('Mobile Phone or User Name') ?>">
                    </div>
                </div>

                <div class="field password required">
                    <label for="pass" class="label"><span><?php /* @escapeNotVerified */ echo __('Password') ?></span></label>
                    <div class="control">
                        <input name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?> class="input-text" id="pass" title="<?php /* @escapeNotVerified */ echo __('Password') ?>" data-validate="{required:true, 'validate-password':true}" placeholder="<?php /* @escapeNotVerified */ echo __('Password') ?>">
                    </div>
                    <div class="secondary"><a class="action remind" href="<?php /* @escapeNotVerified */ echo $block->getForgotPasswordUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Forgot Your Password?') ?></span></a></div>
                </div>
                <div class="actions-toolbar">
                    <div class="primary"><button type="submit" class="action login primary" name="send" id="send2"><span><?php /* @escapeNotVerified */ echo __('Sign In') ?></span></button></div>
                    
                </div>
				
				<div class="bottom-custom-sign-up">
					<span><?php echo __('Don\'t have an account?') ?></span>
					<a href="<?php echo $block->getUrl('customer/account/create'); ?>"><?php echo __('Sign Up') ?></a>
				</div>
                <?php echo $block->getChildHtml('form_additional_info'); ?>
                
            </fieldset>
        </form>
    </div>
</div>
