<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\Resetpassword $block */
?>
<form onsubmit="return false;"
      method="post"
      <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?>
      id="form-validate"
      class="form password reset"
      data-mage-init='{"validation":{}}'>
      <div class="forget-top-img">
            <?php $url = $block->getUrl("pub/media/wysiwyg/"); $url = str_replace("index.php/","",$url);?>
        <img src="<?php echo $url ?>reset-img2.jpg"/>
        <h3>Change Your Password</h3>
      </div>
    <fieldset class="fieldset" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields'); ?>">
        <div class="field password required">
           <!--  <label class="label" for="password"><span><?php // /* @escapeNotVerified */ echo __('New Password'); ?></span></label> -->
            <div class="control">
                <input type="password" class="input-text" name="password" id="password" data-validate="{required:true, 'validate-password':true}" autocomplete="off" placeholder="<?php /* @escapeNotVerified */ echo __('New Password'); ?>">
            </div>
        </div>
        <div class="field confirmation required">
            <!-- <label class="label" for="password-confirmation"><span><?php // /* @escapeNotVerified */ echo __('Confirm New Password'); ?></span></label> -->
            <div class="control">
                <input type="password" class="input-text" name="password_confirmation" id="password-confirmation" data-validate="{required:true,equalTo:'#password'}" autocomplete="off" placeholder="<?php /* @escapeNotVerified */ echo __('Confirm New Password'); ?>">
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" id="submit" class="action submit primary"><span><?php /* @escapeNotVerified */ echo __('Submit'); ?></span></button>
        </div>
    </div>
</form>
<div class="forgotpassword-note" id="redirect" style="display:none"></div>
<script>
require([
    'jquery',
    'mage/mage'
], function($){
    $( "#submit" ).click(function() {
        if($('#form-validate').validation('isValid')){
            $.ajax({
               url: "<?php /* @escapeNotVerified */ echo $block->getUrl('themecafe_otpverification/account/resetpasswordpost', ['_query' => ['id' => $block->getCustomerId(), 'token' => $block->getResetPasswordLinkToken()]]); ?>",
               type: 'post',
               data:  {'password':$('input[name="password"]').val(),'password_confirmation':$('input[name="password_confirmation"]').val()},
               dataType: 'json',
               showLoader: true,
               success: function (res) {
                   if(res.success){
                       $('#form-validate').css('display','none');
                       $('#redirect').css('display','block');
                       $('#redirect').html('<span>You successfully updated your password <b><a href="<?php echo $block->getUrl('customer/account/login');?>" class="login-link">click here</a></b> to login.</span>')
                   }
               }
           });
        }
    });
});
</script>
